# Generated by Django 5.1.5 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("video", "0003_watchlater_video_watch_later_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "videos",
                    models.ManyToManyField(related_name="playlists", to="video.video"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
