# Generated by Django 5.1.5 on 2025-05-01 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("video", "0003_watchlater_video_watch_later_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата редактирования"
                    ),
                ),
                ("text", models.TextField()),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("dislikes_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users_disliked_comment",
                    models.ManyToManyField(
                        related_name="disliked_comments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "users_liked_comment",
                    models.ManyToManyField(
                        related_name="liked_comments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="video.video",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
