# Generated by Django 5.1.3 on 2025-04-15 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_subscribers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribers",
        ),
        migrations.AddField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(
                related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
