FROM python:3.12.7-slim

WORKDIR /back

COPY ../backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../backend .
EXPOSE 8888
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
CMD ["sh", "-c", "python manage.py runserver 0.0.0.0:8888"]