# Generated by Django 5.1.5 on 2025-04-27 12:56

import apps.video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(upload_to=apps.video.models.video_preview_upload_to),
        ),
    ]
