# Generated by Django 5.1.5 on 2025-04-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_video_preview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchLater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("made_action_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="video.video"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddField(
            model_name="video",
            name="watch_later_users",
            field=models.ManyToManyField(
                related_name="videos_to_watch_later",
                through="video.WatchLater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
