# Generated by Django 5.1.3 on 2025-02-06 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="likeshistory",
            old_name="liked_at",
            new_name="made_action_at",
        ),
        migrations.RenameField(
            model_name="watcheshistory",
            old_name="watched_at",
            new_name="made_action_at",
        ),
        migrations.CreateModel(
            name="DislikesHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("made_action_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="video.video"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddField(
            model_name="video",
            name="users_disliked_video",
            field=models.ManyToManyField(
                related_name="disliked_videos",
                through="video.DislikesHistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
