# Generated by Django 5.1.5 on 2025-02-04 10:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True, upload_to=core.models.profile_photo_upload_to
            ),
        ),
    ]
